name: Check new release
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
jobs:
  check-new-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1.0.0
      - name: Check update
        run: |
          echo current_version=$(npm view deno-bin version) | tee --append "$GITHUB_ENV"
          echo latest_version=$(deno -V | awk '{print $2}') | tee --append "$GITHUB_ENV"
      - name: Bump
        if: env.latest_version != env.current_version
        run: |
          npm version ${{ env.latest_version }}
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > .npmrc
          npm publish --ignore-scripts
